workflows:
  ios-ipa:
    name: iOS IPA
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default
      flutter: stable
    scripts:
      - name: Obtener dependencias
        script: flutter pub get
      - name: Instalar pods
        script: cd ios && pod install
      - name: Compilar iOS sin firma
        script: flutter build ios --release --no-codesign
      - name: Empaquetar IPA
        script: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload/
          zip -r $CM_BUILD_DIR/buy_and_stock.ipa Payload
    artifacts:
      - buy_and_stock.ipa
