// File generated by manual configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBU8AMSfesSYj0-Dsdb_xT_DeJc-1HXuTA',
    appId: '1:732132166753:android:2b6394799c3e666c38ae20',
    messagingSenderId: '732132166753',
    projectId: 'mi-lista-compras',
    storageBucket: 'mi-lista-compras.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKYQBFMFPTt5mvV4_Oq57bQkLWRyMs6A',
    appId: '1:732132166753:ios:1e30b029ad6db4db38ae20',
    messagingSenderId: '732132166753',
    projectId: 'mi-lista-compras',
    storageBucket: 'mi-lista-compras.firebasestorage.app',
    iosBundleId: 'com.buy-stock.app',
  );
}
